{
 "title": "memory",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "show tag values from memory_statistics with key = \"instance\""
   }
  ]
 },
 "panels": [
  {
   "title": "total count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'GAUGE' AND \"facade\" =~ /^dbnum_*/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbnum_*/" }
     ]
    }
   ]
  },
  {
   "title": "expired count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'GAUGE' AND \"facade\" =~ /^dbexp_*/) AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbexp_*/" }
     ]
    }
   ]
  },
  {
   "title": "count by db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_facade",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'GAUGE' AND \"facade\" =~ /^dbnum_*/) AND $timeFilter GROUP BY \"facade\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbnum_*/" }
     ]
    }
   ]
  },
  {
   "title": "expired by db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_facade",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'GAUGE' AND \"facade\" =~ /^dbexp_*/) AND $timeFilter GROUP BY \"facade\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^dbexp_*/" }
     ]
    }
   ]
  },
  {
   "title": "total memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT last(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'GAUGE' AND \"facade\" = 'total_memory') AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GAUGE" },
      { "condition": "AND", "key": "facade", "operator": "=", "value": "total_memory" }
     ]
    }
   ]
  },
  {
   "title": "Last update time",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "dateTimeAsIso",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'GAUGE' AND \"facade\" = 'last_update') AND $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "count by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_facade",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'COUNTER' AND \"facade\" =~ /^count_*/) AND $timeFilter GROUP BY \"facade\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "COUNTER" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^count_*/" }
     ]
    }
   ]
  },
  {
   "title": "memory usage by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_facade",
     "groupBy": [
      { "params": [ "facade" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "memory_statistics",
     "query": "SELECT sum(\"value\") FROM \"30days\".\"memory_statistics\" WHERE (\"instance\" =~ /^$instance$/ AND \"module\" = 'memory' AND \"type\" = 'COUNTER' AND \"facade\" =~ /^memory_*/) AND $timeFilter GROUP BY \"facade\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "module", "operator": "=", "value": "memory" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "COUNTER" },
      { "condition": "AND", "key": "facade", "operator": "=~", "value": "/^memory_*/" }
     ]
    }
   ]
  }
 ]
}