name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
        check-latest: false
    - name: Build with Maven
      run: mvn -B install test
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
